baseurl = "https://liuyanguu.github.io/"
publishDir  = "D:/OneDrive/R_Blog_Pub/liuyanguu.github.io"
languageCode = "en-us"
title = "Welcome to my blog"
theme = "hugo-xmag"
googleAnalytics = "UA-122668586-1"
disqusShortname = "liuyanguu"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "About Me"
    url = "/about me/"
    weight = 5


[params]
    description = "Yang's research blog built through R blogdown and R Markdown."
    summary_length = 300
    github_edit = "https://github.com/liuyanguu/Blogdown/edit/master/hugo-xmag/content/"
    footer = "Acknowledgement to Yihui Xie for R Blogdown and hugo-xmag theme"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
    
[params.banner]
    src = "ocean 2.jpg"
    alt = "Text on Image"
